version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: dbFinancialControl
    environment:
      POSTGRES_USER: moura
      POSTGRES_PASSWORD: 1807
      POSTGRES_DB: dbFinancialControl
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
