spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://dbFinancialControl:5432/dbFinancialControl #container: api - container: banco de dados
    url: jdbc:postgresql://localhost:5432/dbFinancialControl #local: api - container: banco de dados
    username: "moura"
    password: 1807
    testOnBorrow: true

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: update

#jwt:
#  secret: viverédesenharsemborracha

